backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/asso/index.md"
        label: "Association"
        name: "asso"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/permaculture/index.md"
        label: "La permaculture"
        name: "permaculture"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/offres/index.md"
        label: "Nos offres"
        name: "offres"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/galerie/index.md"
        label: "Galerie"
        name: "galerie"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/potagers/index.md"
        label: "Potager"
        name: "potagers"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: Image, name: image, widget: image }
